#!/bin/sh
# Runs the recorder application from the 'examples' directory, optionally
# using the provided Python version.
# ./runrecorder [3|2]

if [ -n $1 ] && [ "$1" = "2" ]; then
	echo Recorder on Python2
	PYTHONPATH=.. python recorder.py
else
	echo Recorder on Python3
	PYTHONPATH=.. python3 recorder.py
fi
